### ISSUE TITLE
Undefined variable at line 88

### ISSUE THREAD

**Issue by Sandertv** [Ad5001/CommandBlocks#2]
Hey! The plugin doesn't work properly because $block isn't defined at line 88, please do so :)

**Comment by Ad5001** [comment]
This is fixed on the version that is on IM I just did not update on github;)

**Comment by Sandertv** [comment]
You mean the opposite? I did get mine from IM forums :P

**Comment by Ad5001** [comment]
What? It worked fine on the computer of my friend...

**Comment by Sandertv** [comment]
That' weird...
