### ISSUE TITLE
Getting 'stuck' in the command

### ISSUE THREAD

**Issue by Sandertv** [Ad5001/CommandBlocks#3]
Hey @Ad5001 the issue with the undefined variable was fixed but I got an annoying glitch where I keep getting 'stuck' in the command. Basically, when I press the redstone lamp with a diamond hoe and enter my command it all goes alright, but when I try to type something in the chat after that it will keep using that as a new command for the command block, this get's fixed when the server restarts.

**Comment by Ad5001** [comment]
Okkkk I will update it... (But I just recorded a video with the one on IM forums and it just worked fine !)

**Comment by Ad5001** [comment]
Okkkk I will update it... (But I just recorded a video with the one on IM forums and it just worked fine !)

**Comment by inxomnyaa** [comment]
14th July, last year. gg, nothing happened.

**Comment by Ad5001** [comment]
I stoped maintaining this plugin when command blocks were out.
